$id: WPSConfigurationDirectory
label: docs/wemake-python-styleguide/*/configuration/ directory
≡:
  ∩:
    - $type: Restriction
      onProperty: octa:isChildOf
      someValuesFrom: WPSVersionDirectory
    - $type: Restriction
      onProperty: octa:fileName
      hasValue: "configuration"
